# Generated by Django 2.2.16 on 2022-09-17 19:34

import django.core.validators
from django.db import migrations, models
import reviews.validators


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='дата публикации'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[reviews.validators.no_me_username, django.core.validators.RegexValidator('(^[\\w.@+-]+\\z)', message='Такие символы нельзя использовать в никнейме')]),
        ),
    ]
