# Generated by Django 2.2.16 on 2022-09-17 19:37

from django.db import migrations, models
import reviews.validators


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20220917_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[reviews.validators.no_me_username, reviews.validators.OnlyAllowedCharacters]),
        ),
    ]
